### ISSUE TITLE
Dark Kranus in Spark Simulator

### ISSUE THREAD

**Issue by SOSFROMTHEDARKNESS** [BluuArc/bf-mt#28]
Kranus (Dark) is showing up as 144/150 sparks (solo) despite not self sparking.

**Comment by BluuArc** [comment]
Can you give further details on the squad used?

**Comment by SOSFROMTHEDARKNESS** [comment]
The squad is just a single dark Kranus.

**Comment by BluuArc** [comment]
Ah, what I was missing to understand was that...
* It's the Omni-Evolution of Dark Kranus
* Said Kranus also had the SP to add the additional attack on SP (option E)

All that put together allowed me to reproduce it

![image](https://user-images.githubusercontent.com/16447522/132799517-57958eb4-230a-4360-93f8-c7310d36d369.png)

I'll see if I can take a look at it this weekend to figure out why (I have a hunch based on some other things I found while trying to figure this out) and fix it.

**Comment by BluuArc** [comment]
After some investigation, I think any units with the following conditions are affected by this scenario:

* Teleporting attack on burst (BB, SBB, UBB)
* Has an extra attack that has a non-zero frame delay

After some skimming of the current units with the above conditions, the affected units are:

* OE Kranus (2 frame delay on SBB and UBB SP, in-game has 0/150 sparks for SBB and 0/198 sparks for UBB)
* OE Aoife (1 frame delay on SP, in-game has 114/160 sparks against 6 enemies with SBB)
* OE Sidonie (1 frame delay on SP, in-game has 220/261 sparks against 6 enemies with SBB)

I have two potential causes in mind that will require more investigation

1. The cause is the unknown teleport value 
2. The cause is a miscalculation in the delay for extra attacks

Currently, teleporting attacks are treated a bit special in that they ignore the frame delay in the given burst entirely in the spark simulator and rely on the specific value for a given teleporting unit. One potential change to be made here depending on how the investigation goes is potentially factoring in the effect's delay value for extra attacks that are teleporting.

If I figure out the teleport value for either Sidonie or Aoife, this would reveal whether the current calculation is correct or not; figuring out Kranus's teleport value won't really help here since the correct calculation would lead to zero sparks while the other two units have a specific non-zero spark value. A non-zero spark value makes it much easier to figure out the teleportation delay of a unit over a zero-spark value because it's typically more frequent to see zero sparks over a specific number of sparks.

I'll see if I can investigate more in the next week or two.

**Comment by SOSFROMTHEDARKNESS** [comment]
Huh interesting. I would've thought that only the teleport delay is being set to 0 and the effect delays are still factored in.

**Comment by BluuArc** [comment]
Unfortunately did not get time this past week to investigate further. Will try to find some time in the coming week.

> I would've thought that only the teleport delay is being set to 0 and the effect delays are still factored in.

From what I call of the discovery process for the teleport delays of a given unit, at least for the ones I calculated, they were tested for a given unit and a specific skill (typically SBB) and whatever value was found was put directly into the spark simulator. Shouldn't be difficult to simply subtract the effect delays to get the true teleport delay, but that'd require verifying each of the known teleport delays for accuracy (mainly to ensure that we're not making calculations more inaccurate by subtracting the effect delays). It'll be something for me to think about at least.

**Comment by BluuArc** [comment]
So I finally got time to calculate Sidonie's delay and found that that the current calculation method for teleporting units is not fully correct. The correct calculation for all teleporting units should be something like `baseTeleportValue + effectDelayOfSkill`, especially for units that have different delays on each attack of the same skill (Kranus has effect delays of 1-1-2 for the 3 attacks on SBB for example). The current incorrect calculation is using just `precalculatedTeleportValue` and completely disregards the effect delay of the skill; all the currently known teleport delays in BFMT (and also to `project-sparkle`) are in the `precalculatedTeleportValue` format.

Therefore the solution is to first change the calculation method and then go through all the known teleporter delays and confirm the correct `baseTeleportValue` (or at least guestimate based on the effect delays of units). The change in calculation method is already done, but checking the teleport delays for accuracy will take some time. Hopefully it won't longer than a couple weeks considering the time I have available to dedicate to this. I'm also thinking of porting this fix over to Project Sparkle since implementation-wise, it's not a huge change like adding extra attack support was.

The incorrect calculation in teleport delays also led me to finding a more correct value for Karna Masta (who has effect delays of 1 and 2 for his two attacks on SBB); this also explains why finding an initial value was so tricky (and not fully correct) because the `precalculatedTeleportValue` method does not account for differing effect delays on the same attack.

Thanks for bringing this to my attention!

**Comment by SOSFROMTHEDARKNESS** [comment]
Nice work! I guess I'll close the issue for now.
